sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t sumugan13/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sumugan13/docker-react npm run test